version: '3.1'
services:
  springboot:
    image: panduladdu/maven-web-app-docker:VERSION
    restart: always
    ports:
    - 8080:8080
    networks:
    - springbootnetwork
networks:
  springboootnetwork:
